### ISSUE TITLE
Slow execution once you hit 38 astrals

### ISSUE THREAD

**Issue by ghost** [Ornicare/Astral-Blessings-Optimizer#2]
How well is this going to scale with the increase in astrals now that hard Jade Palace is out?  I'm running it with 38 Astrals and it's been going for a few minutes.  Even when I had 35 it took 10x longer than when I had 32.

Any ideas?

**Comment by ghost** [comment]
How odd.  I downloaded the binary release instead of the version I compiled and it was almost instant.  Not idea why, but it was slowly just increasing the ram usage over several minutes.

**Comment by Ornicare** [comment]
Sorry for the late answer (i hardly play the game at this moment).
I optimized the code quite a bit so all the configuration finish in less
than a minute on my machine (to be precise, i add some code to cache all
the calculations, and some code to remember all the equivalent paths)

Best Regards,

Antoine

Le sam. 18 sept. 2021 à 08:34, Arath Sin ***@***.***> a
écrit :

**Comment by ghost** [comment]
> i hardly play the game at this moment

That's really too bad!  The tool is amazing, I've run it for several top bards in our guild and all the other DPS are jealous there's nothing like that for their classes!
